name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: my-app
  REPO_NAME: manasab805/my-app

jobs:
  build-and-scan:
    name: Build, Scan & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:main
            ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:sha-${{ github.sha }}

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@master

      - name: Run Trivy Scan
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:sha-${{ github.sha }}

  update-deployment:
    name: Update Kubernetes Deployment
    runs-on: ubuntu-latest
    needs: build-and-scan

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync with remote main
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Update deployment image
        run: |
          NEW_IMAGE="${REGISTRY}/${REPO_NAME}:sha-${GITHUB_SHA}"
          echo "Updating deployment to use image: $NEW_IMAGE"
          sed -i "s|image: ghcr.io/.*|image: ${NEW_IMAGE}|g" kubernetes/deployment.yaml
          grep -A 1 "image:" kubernetes/deployment.yaml

      - name: Commit and push changes
        run: |
          git add kubernetes/deployment.yaml
          git commit -m "Update deployment image to $NEW_IMAGE" || echo "No changes to commit"
          git push origin main --force
