name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: my-app
  USERNAME: manasab805  # lowercase GitHub username

jobs:
  build-and-scan:
    name: Build, Scan & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:main
            ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}

      - name: Set up Trivy cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: cache-trivy-${{ github.sha }}
          restore-keys: cache-trivy-

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          scan-ref: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true   
          cache: true

  update-deployment:
    name: Update Kubernetes Deployment
    runs-on: ubuntu-latest
    needs: build-and-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Sync with remote main
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Update Deployment Image
        run: |
          NEW_IMAGE="${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}"
          echo "Updating deployment to use image: $NEW_IMAGE"
          sed -i "s|image: .*|image: ${NEW_IMAGE}|g" kubernetes/deployment.yaml
          grep -A 1 "image:" kubernetes/deployment.yaml
          
      - name: Commit and Push Deployment Update
        env:
          GH_PAT: ${{ secrets.GHCR_PAT }}
        run: |
          git add kubernetes/deployment.yaml
          git commit -m "Update deployment image to $NEW_IMAGE" || echo "No changes to commit"
          git push https://$GH_PAT@github.com/${{ github.repository }}.git HEAD:main

